<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414222118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE update (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE utilisateur_evenement DROP CONSTRAINT fk_user_event_user');
        $this->addSql('ALTER TABLE utilisateur_evenement DROP CONSTRAINT fk_user_event_event');
        $this->addSql('DROP TABLE utilisateur_evenement');
        $this->addSql('ALTER TABLE etablissement ADD relation VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE etablissement DROP nom');
        $this->addSql('ALTER TABLE etablissement DROP ville');
        $this->addSql('ALTER TABLE etablissement ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE etablissement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE etablissement RENAME COLUMN adresse TO return');
        $this->addSql('ALTER TABLE evenement ADD relation VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE evenement DROP titre');
        $this->addSql('ALTER TABLE evenement DROP date_evenement');
        $this->addSql('ALTER TABLE evenement ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE evenement ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE evenement RENAME COLUMN lieu TO return');
        $this->addSql('ALTER TABLE filiere DROP CONSTRAINT fk_filiere_etablissement');
        $this->addSql('DROP INDEX IDX_2ED05D9EFF631228');
        $this->addSql('ALTER TABLE filiere ADD return VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE filiere ADD relation VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE filiere DROP libelle');
        $this->addSql('ALTER TABLE filiere DROP description');
        $this->addSql('ALTER TABLE filiere DROP etablissement_id');
        $this->addSql('ALTER TABLE filiere ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE filiere ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX utilisateur_email_key');
        $this->addSql('ALTER TABLE utilisateur ADD return VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur DROP email');
        $this->addSql('ALTER TABLE utilisateur DROP nom');
        $this->addSql('ALTER TABLE utilisateur DROP roles');
        $this->addSql('ALTER TABLE utilisateur ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE utilisateur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE utilisateur RENAME COLUMN password TO relation');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE utilisateur_evenement (utilisateur_id INT NOT NULL, evenement_id INT NOT NULL, PRIMARY KEY (utilisateur_id, evenement_id))');
        $this->addSql('CREATE INDEX IDX_6B889D32FB88E14F ON utilisateur_evenement (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_6B889D32FD02F13 ON utilisateur_evenement (evenement_id)');
        $this->addSql('ALTER TABLE utilisateur_evenement ADD CONSTRAINT fk_user_event_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur_evenement ADD CONSTRAINT fk_user_event_event FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE update');
        $this->addSql('ALTER TABLE etablissement ADD nom VARCHAR(150) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD adresse VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE etablissement ADD ville VARCHAR(100) DEFAULT \'Lomé\'');
        $this->addSql('ALTER TABLE etablissement DROP return');
        $this->addSql('ALTER TABLE etablissement DROP relation');
        $this->addSql('ALTER TABLE etablissement ALTER id SET DEFAULT nextval(\'etablissement_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE etablissement ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE evenement ADD titre VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE evenement ADD date_evenement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE evenement DROP relation');
        $this->addSql('ALTER TABLE evenement ALTER id SET DEFAULT nextval(\'evenement_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE evenement ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE evenement RENAME COLUMN return TO lieu');
        $this->addSql('ALTER TABLE filiere ADD libelle VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE filiere ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE filiere ADD etablissement_id INT NOT NULL');
        $this->addSql('ALTER TABLE filiere DROP return');
        $this->addSql('ALTER TABLE filiere DROP relation');
        $this->addSql('ALTER TABLE filiere ALTER id SET DEFAULT nextval(\'filiere_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE filiere ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE filiere ADD CONSTRAINT fk_filiere_etablissement FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_2ED05D9EFF631228 ON filiere (etablissement_id)');
        $this->addSql('ALTER TABLE utilisateur ADD email VARCHAR(180) NOT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD nom VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD roles JSONB DEFAULT \'["ROLE_USER"]\' NOT NULL');
        $this->addSql('ALTER TABLE utilisateur DROP return');
        $this->addSql('ALTER TABLE utilisateur ALTER id SET DEFAULT nextval(\'utilisateur_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE utilisateur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE utilisateur RENAME COLUMN relation TO password');
        $this->addSql('CREATE UNIQUE INDEX utilisateur_email_key ON utilisateur (email)');
    }
}
