<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604235654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE filiere_etablissement (filiere_id INT NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (filiere_id, etablissement_id))');
        $this->addSql('CREATE INDEX IDX_6707593E180AA129 ON filiere_etablissement (filiere_id)');
        $this->addSql('CREATE INDEX IDX_6707593EFF631228 ON filiere_etablissement (etablissement_id)');
        $this->addSql('CREATE TABLE update (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593E180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE etablissement ADD nom VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD ville VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE evenement ADD titre VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE evenement ADD date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE evenement ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE evenement ADD etablissement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('CREATE INDEX IDX_B26681EFF631228 ON evenement (etablissement_id)');
        $this->addSql('ALTER TABLE filiere ADD nom VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE filiere ADD description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE filiere ADD debouches TEXT NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593E180AA129');
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593EFF631228');
        $this->addSql('DROP TABLE filiere_etablissement');
        $this->addSql('DROP TABLE update');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE etablissement DROP nom');
        $this->addSql('ALTER TABLE etablissement DROP ville');
        $this->addSql('ALTER TABLE etablissement DROP type');
        $this->addSql('ALTER TABLE etablissement DROP description');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681EFF631228');
        $this->addSql('DROP INDEX IDX_B26681EFF631228');
        $this->addSql('ALTER TABLE evenement DROP titre');
        $this->addSql('ALTER TABLE evenement DROP date_debut');
        $this->addSql('ALTER TABLE evenement DROP description');
        $this->addSql('ALTER TABLE evenement DROP etablissement_id');
        $this->addSql('ALTER TABLE filiere DROP nom');
        $this->addSql('ALTER TABLE filiere DROP description');
        $this->addSql('ALTER TABLE filiere DROP debouches');
    }
}
